# Generated by Django 2.0.1 on 2018-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanguo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('defence', models.IntegerField()),
                ('defence_add', models.IntegerField()),
                ('soldier_recover', models.IntegerField()),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '英雄',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='CityOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city_id', models.IntegerField()),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'city_ownership',
            },
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('leadership', models.IntegerField()),
                ('force', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('politics', models.IntegerField()),
                ('charm', models.IntegerField()),
                ('score', models.IntegerField()),
                ('is_enabled', models.IntegerField(choices=[(0, '停用'), (1, '启用')], default=1)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '英雄',
                'db_table': 'heroes',
            },
        ),
        migrations.CreateModel(
            name='HeroOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('hero_id', models.IntegerField()),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'hero_ownership',
            },
        ),
        migrations.CreateModel(
            name='UserBattleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('soldier', models.IntegerField()),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user_battle_info',
            },
        ),
        migrations.CreateModel(
            name='UserEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=300)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
