# Generated by Django 2.0.1 on 2018-03-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguo', '0002_cities_cityownership_heroes_heroownership_userbattleinfo_userex'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='heroes',
            name='introduce',
            field=models.TextField(default=''),
        ),
    ]
