# Generated by Django 2.0.1 on 2018-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguo', '0003_auto_20180303_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='init_defence',
            field=models.IntegerField(default=1000),
        ),
    ]
