# Generated by Django 2.0.1 on 2018-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguo', '0004_cities_init_defence'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityownership',
            name='soldier',
            field=models.IntegerField(default=0),
        ),
    ]
