# Generated by Django 2.0.1 on 2018-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguo', '0005_cityownership_soldier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'battle_message',
            },
        ),
    ]
