# Generated by Django 2.0.1 on 2018-03-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanguo', '0006_battlemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlemessage',
            options={'verbose_name_plural': '消息'},
        ),
    ]
